[build]
  # Root se hi build hoga
  command = "npm run build:client"
  publish = "dist/spa"

[functions]
  # Functions ka folder yahi hai tumhare project me
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
